export enum ContextModule {
  aboutTheWork = "aboutTheWork",
  artistHeader = "artistHeader",
  artistsToFollowRail = "artistsToFollowRail",
  artworkGrid = "artworkGrid",
  artworkSidebar = "artworkSidebar",
  auctionRail = "auctionRail",
  categoryRail = "categoryRail",
  collectionDescription = "collectionDescription",
  featuredArtistsRail = "featuredArtistsRail",
  footer = "footer",
  header = "header",
  homeBanner = "homeBanner",
  intextTooltip = "intextTooltip",
  otherWorksByArtistRail = "otherWorksByArtistRail",
  otherWorksByGalleryRail = "otherWorksByGalleryRail",
  relatedArtistsRail = "relatedArtistsRail",
  relatedWorksRail = "relatedWorksRail",
  worksByPopularArtistsRail = "worksByPopularArtistsRail",
  worksForSaleRail = "worksForSaleRail",
}
